trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest' # Choose an appropriate image for your SQL Server tools

steps:

- task: CopyFiles@2
  displayName: 'Copy SQL Script to Artifact Staging Directory'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/sql/'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: SQLScripts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'SQLScripts'






trigger:
- master

pool:
  vmImage: 'windows-latest'

jobs:
- job: Build
  steps:
  - script: |
      # Your build commands go here
      # For example, generate SQL files

  - task: CopyFiles@2
    displayName: 'Copy SQL Files'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/path/to/sql/files'
      Contents: '*.sql'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/SQLFiles'

  - task: UniversalPackages@0
    displayName: 'Publish SQL Files'
    inputs:
      command: 'publish'
      publishDirectory: '$(Build.ArtifactStagingDirectory)/SQLFiles'
      feedsToUse: 'select'
      vstsFeed: '<Your-Azure-Artifacts-Feed-Name>'
      vstsFeedPublish: true
      vstsFeedPackagePublish: true
