trigger:
- master

pool:
  vmImage: 'windows-latest'

jobs:
- job: Build
  steps:
  - script: |
      # Your build commands go here
      # For example, generate SQL files

  - task: CopyFiles@2
    displayName: 'Copy SQL Files'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/path/to/sql/files'
      Contents: '*.sql'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/SQLFiles'

  - task: ArchiveFiles@2
    displayName: 'Archive SQL Files'
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/SQLFiles'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/SQLFiles.zip'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish SQL Files Artifact'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/SQLFiles.zip'
      artifactName: 'SQLFiles'

- job: PublishToArtifactsFeed
  dependsOn: Build
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UniversalPackages@0
    displayName: 'Publish SQL Files to Artifacts Feed'
    inputs:
      command: 'publish'
      publishDirectory: '$(Build.ArtifactStagingDirectory)'
      feedsToUse: 'select'
      vstsFeed: '<Your-Azure-Artifacts-Feed-Name>'
      vstsFeedPublish: true
      vstsFeedPackagePublish: true
      packagePublishDescription: 'SQL Files Package'
      versionOption: 'patch'
